# Config for workstyle
#
# Format:
# "pattern" = "icon"
#
# The pattern will be used to match against the application name, class_id or WM_CLASS.
# The icon will be used to represent that application.
#
# Note if multiple patterns are present in the same application name,
# precedence is given in order of apparition in this file.

"github -" = ""
"youtube -"=""
"netflix -"="󰝆"
"google -" = ""
"facebook -" = ""
"google search" = ""
"gmail" = "󰊫"
"reddit" = ""
"hacker news" = ""
"index" = ""
"code - oss" = "󰨞"
"rust" = ""
"python" = ""
"node" = ""
"private browsing" = ""
"chrome" = ""
"firefox" = ""
"file manager" = ""
"nvim" = ""
"vim" = ""
"gthumb" = ""
"vlc" = "󰕼"
"torrent" = ""
"volume"=""
"music" = ""
"alacritty" = ""

[other]
fallback_icon = ""
deduplicate_icons = false
